[project]
name = "tokenization-exploration"
version = "0.1.0"
description = "Exploration project to test a custom BPE tokenizer"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.8.5",
    "jupyter>=1.1.1",
    "lxml>=6.1.1",
    "pubmed-parser>=0.5.1",
    "s3fs>=2026.2.0",
    "tokenizers>=0.22.2",
    "transformers>=5.9.0",
]
